[package]
name = "bilive-danmaku"
version = "0.1.2"
edition = "2021"
members = ["./src/test", "./examples"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
futures-util = { version = "*", optional = true }
surf = { version = "*", optional = true }
brotli = { version = "3.3.4", optional = true }
deflate = { version = "1.0.0", optional = true }
js-sys = { version = "0.3.60", optional = true }
wasm-bindgen-futures = { version = "0.4.33", optional = true }
async-trait = "0.1.61"

[dependencies.bincode]
version = "1.3.3"
optional = true

[dependencies.tokio]
version = "1.24.1"
optional = true
features = ["time", "sync", "rt"]

[dependencies.tokio-tungstenite]
version = "*"
features = ["native-tls"]
optional = true

[dependencies.gloo-net]
version = "0.2.5"
optional = true

[dependencies.gloo-timers]
version = "0.2.5"
optional = true
features = ["futures"]

[dependencies.futures]
version = "0.3.25"


[features]
default = ["connect", "rt_wasm"]
full = ["connect", "bincode", "deflate", "json"]
connect = ["dep:futures-util", "dep:brotli", "dep:surf", "event"]
rt_tokio = ["dep:tokio", "dep:tokio-tungstenite"]
rt_wasm = [
    "dep:js-sys",
    "dep:gloo-net",
    "dep:gloo-timers",
    "dep:wasm-bindgen-futures"
]
bincode = ["dep:bincode"]
deflate = ["dep:deflate", "connect"]
event = []
json = []
debug = []
verbose = []
