[package]
name = "bilive-danmaku"
version = "0.1.1"
edition = "2021"
members = ["./src/test"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
futures-util = { version = "*", optional = true }
surf = { version = "*",  optional = true }
brotli = { version = "3.3.4", optional = true }
deflate = { version = "1.0.0", optional = true }
async-trait = "0.1.61"

[dependencies.bincode]
version = "1.3.3"
optional = true

[dependencies.tokio]
version = "*"
optional = true
features = ["time", "sync", "rt"]

[dependencies.tokio-tungstenite]
version = "*"
features = ["native-tls"]
optional = true

[features]
default = [
    "connect", 
    "rt_tokio",
]
full = ["connect", "bincode", "deflate", "json"]
connect = [
    "dep:futures-util",
    "dep:brotli",
    "dep:surf",
    "event",
]
rt_tokio = [
    "dep:tokio",
    "dep:tokio-tungstenite",
]
bincode = ["dep:bincode"]
deflate = ["dep:deflate", "connect"]
event = []
json = []
debug = []
verbose = []
