[package]
name = "bilive-danmaku"
version = "0.0.1-wip"
edition = "2021"
members = ["./src/test"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0.136", features = ["derive"]}
serde_json = "1.0.79"
tokio = {version = "1.18.2", features = ["full"], optional = true}
futures-util = {version= "*" , optional = true}
tokio-tungstenite = {version = "0.17.1", features = ["native-tls"], optional = true}
reqwest = {version = "*", optional = true}
brotli = {version = "3.3.4", optional = true}
deflate = {version = "1.0.0", optional = true}
[dependencies.bincode]
version = "1.3.3"
optional = true

[features]
default = ["connect"]
connect = ["dep:tokio", "dep:futures-util", "dep:brotli", "dep:reqwest", "dep:tokio-tungstenite", "event"]
bincode = ["dep:bincode"]
deflate = ["dep:deflate", "connect"]
event = []
json = []
debug = []
verbose = []