name: Publish Rust Package

on:
  push:
    branches:
      - release

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install cargo-release
        run: cargo install cargo-release

      - name: Release package
        env:
          CRATE_NAME: ${{ secrets.CRATE_NAME  }}
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          cargo release --dry-run --skip-publish --message "Release v%s"
          cargo release --skip-publish --message "Release v%s"
          cargo publish --manifest-path $CRATE_NAME/Cargo.toml --token $CRATES_IO_TOKEN
