name: Rust Check

on:
  push:
    branches: [ "master", "publish" ]
  pull_request:
    branches: [ "master", "publish" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Build default
      run: cargo build --verbose --features default
    - name: Build rt-tokio
      run: cargo build --verbose --features rt_tokio
    - name: Run tests
      run: cargo test --verbose
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Check code style for default
      run: cargo clippy --features default -- -D warnings
    - name: Check code style for rt-tokio
      run: cargo clippy --features rt_tokio -- -D warnings
